# Generated by Django 4.2.5 on 2023-09-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('infoSymbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='')),
                ('infoTitle', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('infoMarket_fa', models.CharField(blank=True, max_length=10, null=True, verbose_name='')),
                ('infoFlowTitle', models.CharField(blank=True, max_length=10, null=True, verbose_name='')),
                ('infoLastTradePDrCotVal', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('infoLastTradeLastChange', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('infoLastTradeLastChangePercentage', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('infoLastPricePClosing', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('infoLastPriceClosingChange', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('infoLastPriceClosingChangePercentage', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('lastDate', models.DateTimeField(blank=True, null=True)),
                ('tradesZTotTran', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('tradesQTotTran5J', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('tradesQTotCap', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('etcMotevasetHajmHarMoamele', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('infoPriceYesterday', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('infoPriceFirst', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('infoDayRangePriceMin', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('infoDayRangePriceMax', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('demands1_1', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('demands1_0', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('demands1_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('demands1_4', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('demands1_5', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('demands1_3', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('tradesArzeshBazar', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('etcArzeshRoozDarayi', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('etcArzeshDaftariDarayi', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('etcAkharinSarmaye', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('etcBedehi', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('etcHoghoghSahebanSaham', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('etcPishbiniDaramad', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('etcSoodKhalesTtm', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('infoPe', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('infoPb', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('infoPs', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('tradesBuyAndSellBuyIVolume', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('tradesBuyAndsellBuy_NVolume', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('tradesBuyAndSellSellIVolume', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('tradesBuyAndSellSellNVolume', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
            ],
        ),
    ]
