# Generated by Django 4.2.5 on 2023-10-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('d', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('dp', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('dt', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('h', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('l', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('p', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('t', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('tg', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('ten', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
                ('ts', models.CharField(blank=True, max_length=30, null=True, verbose_name='')),
            ],
        ),
    ]
