# Generated by Django 4.2.5 on 2023-10-04 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0002_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
